### ISSUE TITLE
UI needs improvement

### ISSUE THREAD

**Issue by jmario74** [IP-CAM/Opencart-v.1.5.6.5-LIGHT-Install-PHP-v.7.4.16#3]
I have tested you version of open cart & it is the fastest i have ever experienced; i also have used it with rocksdb with very impressive results, the UI however is not pleasing to the eye & to be honest down right ugly to me; but beauty is in the eye of the beholder; unfortunately i am not one. please improve the UI much like the original which i find is still able to compete with the modern eComs out there and your logo is quite glaring in its boldness; i was blinded by it. a website is like an exotic car it has to be a combination of styling & performance to be successful.

**Comment by IP-CAM** [comment]
Tks for your comment. I am using the famous Merkent Theme as default Theme in the LIGHT Version, and I am very pleased with it, technically as well as functionally. And everybody is free, to 'manipulate' the Theme Stylesheet, to make it look as planned. A 'basic' dark and a bright Stylesheet already exist, and it only within the 'regular' CSS Bootstrap Knowledge of a User, to change/move/edit, whatever on likes, code-wise, size-wise and color-wise. 
Good Luck! :)
Ernie

**Comment by jmario74** [comment]
Appreciate the reply Ernie, I am still a big fan of your work; thanks for
not abandoning the trusty old 1.5.6.5rc, I got it running on
php7.3/nginx/mariadb(rocksdb) and can share that process if anybody is
interested. it is more time consuming to do the content & configure the
website than editing some code to get it running; you're right i am just a
lazy coder and like to get everything out of the box when i can but that is
not always the case, can't get everything.

**Comment by IP-CAM** [comment]
Well, I have all my 1.5.6.5 Test Sites working on PHP v.7.4.16, and famous Coder Condor2 (xxvirusxx) once modified the 'Stock' Version 1.5.6.5_rc, to possibly work with PHP v.8.x as well, by making a minor modification to some Code. I never found time yet, to make further PHP v.8.x Tests, but I'm quite sure, that 1.5.6.5 will also be fully capable to use it, possibly with the exception of a few VqMods and/or Modules, then required, to be upgraded. 
Ernie
[https://github.com/IP-CAM/Opencart-v.1.5.6.5_rc-Install-w.PHP-v.8.x-Thumbfix]
(https://github.com/IP-CAM/Opencart-v.1.5.6.5_rc-Install-w.PHP-v.8.x-Thumbfix)

**Comment by jmario74** [comment]
Hello Ernie I use php7.3 because PHPCPP has not been updated yet to later
versions & i use that to develop c++ extensions for php. I had a second run
with your OC but i can't seem to be able to tailor it to my website design,
i try not to do a lot of coding because of the work i have to do with the
content; i tried the agnes theme with your OC but ran into some problems;
maybe you can make the themes more flexible so the website can be
designed to look & feel a certain way not just a fixed way.

**Comment by IP-CAM** [comment]
Well, you better should use Opencart V-Pro:
https://github.com/IP-CAM/Opencart-v.1.5.6.5-V-PRO-Install-PHP-v.7.4.16
or then the 'basic' OC-1.5.6.5_rc:
https://github.com/IP-CAM/Opencart-v.1.5.6.5_rc-Install-w.PHP-v.8.x-Thumbfix
if you like to add a 'regular' 1.5.6.4_type Custom Theme. OC LIGHT has partly been custom-designed to match the famous Merkent Theme.

**Comment by jmario74** [comment]
thanks Ernie, i'll give both projects a run.
